name: Docker Image CI

on:
  push:
    branches:
      - master  # Trigger on push to the 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Login to Docker Hub using secrets
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myimg .

      # Step 4: Push Docker image to Docker Hub
      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myimg
