name: Docker Image CI

on:
  push:
    branches:
      - master  # Trigger on push to the 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
     
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

     
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myimg .

     
      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myimg
