on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Before listing files'
        run: ls

      - name: Checkout code again
        uses: actions/checkout@v3

      - name: 'After listing files'
        run: ls
